Сделала разметку внутренней страницы
htmlacademy-htmlcss/1486905-nerds-31 pull request #3
Opened 2021-05-23 05:29 UTC by KoshkinaECat

Сделала разметку внутренней страницы+исправила замечания на главной

2021-05-23 14:21 UTC, Zakamsky requested changes
Работа отличная, видно что ты старалась, спасибо за форматирование!
Замечаний не много, но давай их все внесем до начала новой темы?

2021-05-23 14:21 UTC, Zakamsky commented on catalog.html
> +  <main>
Тут кажется опять немного мусор остался... или я не понял идеи.

2021-05-23 14:21 UTC, Zakamsky commented on catalog.html
> +          <p><meter min="0" max="15000" value="10000">10000</meter></p>
Классная идея с `<meter>` но к сожалению у нас два значения у бегунка, а поддерживается только одно.
тут нет нужды в лишней семантике, это сложный элемент, и он скорее вспомогательный, важная информация (точные значения минимума и максимума) лежит в инпутах. 
Давай пока оставим так, а потом будет отдельная демка по этому элементу.

2021-05-23 14:21 UTC, Zakamsky commented on catalog.html
> +          <label>до<input type="text" value="15000"></label>
А почему текст? можно написать туда что нибудь буквами?

2021-05-23 14:21 UTC, Zakamsky commented on catalog.html
> +            </li>
Обычно у студентов ломается радио, а у тебя наоборот немножко. =)

Посмотри внимательно какая информация приходит на сервер, есть польза от нее?

Главное отличие радио и чекбоксов - все радио это одно поле, поэтому у них ВСЕГДА одно имя, и разные вэлью.

У чекбоксов два варианта:
1. разные имена. тогда мы увидим какие чекнтуы.
2. одинаковые имена, но с разными вэлью, тогда на сервер придет массив с именем полей и в нем будет перечисление вэлью которые чекнуты. 

второй способ обычно сложнее и реже используется.

2021-05-23 14:21 UTC, Zakamsky commented on catalog.html
> +            <li>ПО НАЗВАНИЮ</li>
а как мы будем сортировать то?
надо хоть что то интерактивное, в принципе подойдут и кнопки и ссылки одинаково.
вообще чаще используются ссылки для каталогов, а для форм фильтров метод=Гет что бы можно было передать урл другу и он увидел ту же сортировку и фильтры. Или закладку сделать.

2021-05-23 14:21 UTC, Zakamsky commented on catalog.html
> +            <li>ПО НАЗВАНИЮ</li>
з.ы. Буквы заглавными лучше делать из стилей. ,Представь что у тебя куча строк таких и завтра захотят все малые, а после завтра только первые буквы большими? можно идти править весь штмл сайта а модно пару правил стилей.
Но это я просто делюсь опытом.

2021-05-23 14:21 UTC, Zakamsky commented on catalog.html
> +          </p>
имеет смысл задать какую то обертку для всех товаров, а внутри нее уже ссылки и прочее, оборачивать ссылкой всю карточку плохая идя т.к. там могут быть кнопки, даже если их пока нет в макете - завтра будут точно.
ну и серое поле в котором описание и цена, оно у каждой карточки есть, просто в одной показано как выглядит при наведении курсора на карточку товара.

2021-05-23 14:21 UTC, Zakamsky commented on catalog.html
> +      </p>
а давай используем какой нибудь интересный тэг со смыслом, например `address`?

2021-05-24 08:02 UTC, KoshkinaECat commented on catalog.html
> +  <main>
Исправила

2021-05-24 08:09 UTC, KoshkinaECat commented on catalog.html
> +          <label>до<input type="text" value="15000"></label>
исправила на Number

2021-05-24 17:08 UTC, Zakamsky requested changes
Отличные доработки, но кажется я тебя запутал.
надо вернуть форму как она была, и убрать филдсеты из сортировки и товаров, я там прокомментировал, как лучше сделать. Надеюсь понятно. если вдруг нет - пиши, обсудим.

2021-05-24 17:08 UTC, Zakamsky commented on catalog.html
> +              <img src="https://via.placeholder.com/359x578" width="359" height="578" alt="Sedona">
Тут тоже путаница - нам не нужно заворачивать товары в форму, ну и для стилизации будет полезно обернуть все товары в какой то блок,  ну и  fieldset тут явно лишний, давай я немного подскажу:
оборачиваем весь раздел в секцию, заголовок уже есть, а в товарах  fieldset меняем на article
т.е. получится такая структура:
<section>
  <h2>Демонстрация товаров</h2>
  <article> ... </article>
  <article> ... </article>
  <article> ... </article>
  <article> ... </article>
</section>

2021-05-25 16:46 UTC, merged